/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as HistorikkRouteImport } from './routes/historikk'
import { Route as InnstillingerRouteImport } from './routes/innstillinger'
import { Route as LopRouteImport } from './routes/lop'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as OktDayRouteImport } from './routes/okt.$day'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorikkRoute = HistorikkRouteImport.update({
  id: '/historikk',
  path: '/historikk',
  getParentRoute: () => rootRouteImport,
} as any)
const InnstillingerRoute = InnstillingerRouteImport.update({
  id: '/innstillinger',
  path: '/innstillinger',
  getParentRoute: () => rootRouteImport,
} as any)
const LopRoute = LopRouteImport.update({
  id: '/lop',
  path: '/lop',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OktDayRoute = OktDayRouteImport.update({
  id: '/okt/$day',
  path: '/okt/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/historikk': typeof HistorikkRoute
  '/innstillinger': typeof InnstillingerRoute
  '/lop': typeof LopRoute
  '/plan': typeof PlanRoute
  '/okt/$day': typeof OktDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/historikk': typeof HistorikkRoute
  '/innstillinger': typeof InnstillingerRoute
  '/lop': typeof LopRoute
  '/plan': typeof PlanRoute
  '/okt/$day': typeof OktDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/historikk': typeof HistorikkRoute
  '/innstillinger': typeof InnstillingerRoute
  '/lop': typeof LopRoute
  '/plan': typeof PlanRoute
  '/okt/$day': typeof OktDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/historikk'
    | '/innstillinger'
    | '/lop'
    | '/plan'
    | '/okt/$day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/historikk'
    | '/innstillinger'
    | '/lop'
    | '/plan'
    | '/okt/$day'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/historikk'
    | '/innstillinger'
    | '/lop'
    | '/plan'
    | '/okt/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRoute
  HistorikkRoute: typeof HistorikkRoute
  InnstillingerRoute: typeof InnstillingerRoute
  LopRoute: typeof LopRoute
  PlanRoute: typeof PlanRoute
  OktDayRoute: typeof OktDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historikk': {
      id: '/historikk'
      path: '/historikk'
      fullPath: '/historikk'
      preLoaderRoute: typeof HistorikkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innstillinger': {
      id: '/innstillinger'
      path: '/innstillinger'
      fullPath: '/innstillinger'
      preLoaderRoute: typeof InnstillingerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lop': {
      id: '/lop'
      path: '/lop'
      fullPath: '/lop'
      preLoaderRoute: typeof LopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/okt/$day': {
      id: '/okt/$day'
      path: '/okt/$day'
      fullPath: '/okt/$day'
      preLoaderRoute: typeof OktDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRoute,
  HistorikkRoute: HistorikkRoute,
  InnstillingerRoute: InnstillingerRoute,
  LopRoute: LopRoute,
  PlanRoute: PlanRoute,
  OktDayRoute: OktDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
